# mysql/redis config
mysql_dsn: "root:123456@tcp(127.0.0.1:3306)/videoone?parseTime=true&loc=Local"
redis_init: true
redis_addr: "127.0.0.1:6379"
redis_password: ""

# common service config
port: "8080"
access_key: ""
secret_access_key: ""

# rtc service config
rtc_app_id: ""
rtc_app_key: ""

# live service config
live_app_name: ""
live_pull_domain: ""
live_push_domain: ""
live_stream_key: ""

# vod service config
vod_space: ""
vod_play_list_id: "{your_vod_play_list_id}"

# Interactive Live scene config
live_timer_enable: true
live_experience_time: 20

# Online KTV scene config
ktv_timer_enable: true
ktv_experience_time: 20

# Duet Singing scene config
owc_timer_enable: true
owc_experience_time: 20