mysql_dsn: "root:123456@tcp(127.0.0.1:3306)/videoone?parseTime=true&loc=Local"
redis_addr: "127.0.0.1:6379"
redis_password: ""
port: "8080"
live_timer_enable: true
live_experience_time: 20
app_id: "{your_vod_appid}"
vod_play_list_id: "{your_vod_play_list_id}"
ktv_timer_enable: true
ktv_experience_time: 20
owc_timer_enable: true
owc_experience_time: 20