package rtc.volcengine.apiexample.examples;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.TextureView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;

import com.ss.bytertc.engine.RTCRoom;
import com.ss.bytertc.engine.RTCRoomConfig;
import com.ss.bytertc.engine.RTCEngine;
import com.ss.bytertc.engine.UserInfo;
import com.ss.bytertc.engine.VideoCanvas;
import com.ss.bytertc.engine.data.EngineConfig;
import com.ss.bytertc.engine.data.ForwardStreamEventInfo;
import com.ss.bytertc.engine.data.ForwardStreamInfo;
import com.ss.bytertc.engine.data.ForwardStreamStateInfo;
import com.ss.bytertc.engine.data.StreamInfo;
import com.ss.bytertc.engine.handler.IRTCRoomEventHandler;
import com.ss.bytertc.engine.handler.IRTCEngineEventHandler;
import com.ss.bytertc.engine.type.ChannelProfile;
import com.ss.bytertc.engine.type.RTCRoomStats;

import java.util.Collections;

import rtc.volcengine.apiexample.BaseActivity;
import rtc.volcengine.apiexample.R;
import rtc.volcengine.apiexample.Utils.ToastUtil;
import rtc.volcengine.apiexample.common.Constants;
import rtc.volcengine.apiexample.common.annotations.ApiExample;

/**
 * @locale zh
 * 功能名称： ByteRTC 跨房转推
 * 功能简单描述：跨房间转发媒体流，指可见用户的媒体流可以同时转发到多个 RTC 房间。
 *             转发目标房间的数量在 RTC 侧没有限制。 本功能适用于以下场景，观众在原来的房间中就能够接收到来自其他房间主播的媒体流。
 * 参考文档： https://www.volcengine.com/docs/6348/104398
 *
 * 此功能涉及的API及回调：
 *     createRTCEngine 创建引擎
 *     destroyRTCEngine 销毁引擎
 *     startAudioCapture 开启音频采集
 *     startVideoCapture 开启视频采集
 *     createRTCRoom 创建RTC房间
 *     joinRoom 进入RTC房间
 *     leaveRoom 离开RTC房间
 *     destroy 销毁RTC房间
 *
 *     startForwardStreamToRooms 开始转发媒体流
 *     stopForwardStreamToRooms  停止转发媒体流
 *
 *     setLocalVideoCanvas 设置本地视频渲染视图
 *     setRemoteVideoCanvas 设置远端视频渲染视图
 *
 *     onRoomStateChanged 房间状态回调
 *     onLeaveRoom 离房回调
 *     onUserJoined 用户加入回调
 *     onUserLeave  用户离开回调
 *
 * Demo实现时的逻辑
 *    本Demo演示功能：在本端房间向其他房间转推媒体流
 *    为了展示简单，所有功能的token都由客户端生成，请在真正接入时视具体情况而定
 */


/**
 * @locale en
 *
 * Function name: BytePlusRTC forward stream across rooms.
 * Function brief: The media streams of visible users can be simultaneously forwarded to multiple RTC rooms. There are no restrictions on the number of target rooms for media forwarding.
 * Notes:
 *   1. For demonstration purposes, all tokens for the functionalities are generated by the client-side TokenGenerator class. However, please adjust accordingly based on the specific circumstances when integrating in a real environment.
 * Reference document: https://docs.byteplus.com/en/docs/byteplus-rtc/docs-104398
 * </pre>
 */
@ApiExample(order = 2, category = R.string.title_media_transmission, name = R.string.title_cross_room_pk)
public class CrossRoomPKActivity extends BaseActivity {

    private FrameLayout localViewContainer;
    private Button btnJoinRoom;
    private Button btnStartTransmit;
    private Button btnStopTransmit;
    private Button btnPauseTransmit;
    private Button btnResumeTransmit;
    private EditText mainRoomIdInput;
    private EditText transmitRoomIdInput;

    RTCEngine rtcEngine;
    RTCRoom rtcRoom;

    boolean isJoined;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cross_room_pk_activity);
        setTitle(R.string.title_cross_room_pk);
        initUI();

        // 创建引擎
        EngineConfig config = new EngineConfig();
        config.context = this;
        config.appID = Constants.APP_ID;
        rtcEngine = rtcEngine.createRTCEngine(config, videoEventHandler);

        // 设置本端渲染视图
        setLocalRenderView();
        // 开启音视频采集
        rtcEngine.startVideoCapture();
        rtcEngine.startAudioCapture();

    }

    private void initUI() {
        localViewContainer = findViewById(R.id.local_view_container);
        btnJoinRoom = findViewById(R.id.btn_join_room);
        btnStartTransmit = findViewById(R.id.btn_start_transmit);
        btnStopTransmit = findViewById(R.id.btn_stop_transmit);
        btnPauseTransmit = findViewById(R.id.btn_pause_transmit);
        btnResumeTransmit = findViewById(R.id.btn_resume_transmit);
        mainRoomIdInput = findViewById(R.id.main_room_input);
        transmitRoomIdInput = findViewById(R.id.transmit_room_input);

        btnJoinRoom.setOnClickListener(v -> {
            String roomId = mainRoomIdInput.getText().toString();
            if (isJoined) {
                leaveRoom();
                isJoined = false;
                btnJoinRoom.setText(getText(R.string.button_join_room));
                return;
            }
            if (TextUtils.isEmpty(roomId)) {
                ToastUtil.showAlert(this, "roomID is null");
                return;
            }
            joinRoom(roomId);
            isJoined = true;
            btnJoinRoom.setText(getText(R.string.button_leave_room));
        });

        btnStartTransmit.setOnClickListener(v -> {
            String roomId = transmitRoomIdInput.getText().toString();
            // 开始转推
            startForwardStreamToRooms(roomId);
        });

        btnStopTransmit.setOnClickListener(v -> {
            if (rtcRoom != null) {
                // 停止转推
                rtcRoom.stopForwardStreamToRooms();
            }
        });

        btnPauseTransmit.setOnClickListener(v -> {
            if (rtcRoom != null) {
                // 暂停转推
                rtcRoom.pauseForwardStreamToAllRooms();
            }
        });

        btnResumeTransmit.setOnClickListener(v -> {
            if (rtcRoom != null) {
                // 恢复转推
                rtcRoom.resumeForwardStreamToAllRooms();
            }
        });

    }

    /**
     * 设置本地渲染视图，支持TextureView和SurfaceView
     */
    private void setLocalRenderView() {
        TextureView textureView = new TextureView(this);
        localViewContainer.removeAllViews();
        localViewContainer.addView(textureView);

        VideoCanvas videoCanvas = new VideoCanvas();
        videoCanvas.renderView = textureView;
        videoCanvas.renderMode = VideoCanvas.RENDER_MODE_HIDDEN;
        // 设置本地视频渲染视图
        rtcEngine.setLocalVideoCanvas(videoCanvas);
    }

    /**
     * 加入房间
     * @param roomId
     */
    private void joinRoom(String roomId) {
        rtcRoom = rtcEngine.createRTCRoom(roomId);
        rtcRoom.setRTCRoomEventHandler(roomEventHandler);
        String token = requestRoomToken(roomId);
        // 用户信息
        UserInfo userInfo = new UserInfo(localUid, "");
        // 设置房间配置
        boolean isAutoPublishAudio = true;
        boolean isAutoPublishVideo = true;
        boolean isAutoSubscribeAudio = true;
        boolean isAutoSubscribeVideo = true;
        RTCRoomConfig roomConfig = new RTCRoomConfig(ChannelProfile.CHANNEL_PROFILE_CHAT_ROOM, "", isAutoPublishAudio, isAutoPublishVideo, isAutoSubscribeAudio, isAutoSubscribeVideo);
        // 加入房间
        rtcRoom.joinRoom(token, userInfo, true, roomConfig);;
    }

    /**
     * 离开房间
     */
    private void leaveRoom() {
        if (rtcRoom != null) {
            rtcRoom.leaveRoom();
            rtcRoom.destroy();
            rtcRoom = null;
        }
    }

    /**
     * 开启转推
     * @param roomId
     */
    private void startForwardStreamToRooms(String roomId) {
        if (TextUtils.isEmpty(roomId)) {
            ToastUtil.showAlert(this, "roomId is null");
            return;
        }

        // 可以向多个房间转推，实例代码仅展示向一个房间转推
        ForwardStreamInfo forwardStreamInfo = new ForwardStreamInfo(roomId, requestRoomToken(roomId));
        if (rtcRoom != null) {
            rtcRoom.startForwardStreamToRooms(Collections.singletonList(forwardStreamInfo));
        }
    }


    /**
     * 房间回调信息
     */
    IRTCRoomEventHandler roomEventHandler = new IRTCRoomEventHandler() {
        @Override
        public void onRoomStateChanged(String roomId, String uid, int state, String extraInfo) {
            super.onRoomStateChanged(roomId, uid, state, extraInfo);
            String info = String.format("roomId:%s, uid:%s, state:%d, extraInfo:%s", roomId, uid, state, extraInfo);
            ToastUtil.showLongToast(CrossRoomPKActivity.this, info);
        }

        @Override
        public void onForwardStreamEvent(ForwardStreamEventInfo[] eventInfos) {
            super.onForwardStreamEvent(eventInfos);
            String msg = String.format("ForwardStreamEvent, roomid:%s, event:%d", eventInfos[0].roomId, eventInfos[0].event.value());
            ToastUtil.showShortToast(CrossRoomPKActivity.this, msg);
        }

        @Override
        public void onForwardStreamStateChanged(ForwardStreamStateInfo[] stateInfos) {
            super.onForwardStreamStateChanged(stateInfos);
            String msg = String.format("ForwardStreamStateChanged, roomid:%s, state:%d, error:%d", stateInfos[0].roomId, stateInfos[0].state.value(), stateInfos[0].error.value());
            ToastUtil.showShortToast(CrossRoomPKActivity.this, msg);
        }

        @Override
        public void onLeaveRoom(RTCRoomStats stats) {
            super.onLeaveRoom(stats);
            ToastUtil.showLongToast(CrossRoomPKActivity.this, "onLeaveRoom, stats:" + stats.toString());
        }

        @Override
        public void onUserJoined(UserInfo userInfo) {
            super.onUserJoined(userInfo);
            ToastUtil.showShortToast(CrossRoomPKActivity.this, "onUserJoined, uid:" + userInfo.getUid());
        }

        @Override
        public void onUserPublishStreamVideo(String streamId, StreamInfo streamInfo, boolean isPublish) {
            ToastUtil.showShortToast(CrossRoomPKActivity.this, "onUserPublishStreamVideo, uid:" + streamInfo.userId + " isPublish:" + isPublish);
        }
    };

    /**
     * 引擎回调信息
     */
    IRTCEngineEventHandler videoEventHandler = new IRTCEngineEventHandler() {
    };

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (rtcEngine != null) {
            rtcEngine.stopAudioCapture();
            rtcEngine.stopVideoCapture();
        }
        if (rtcRoom != null) {
            rtcRoom.destroy();
            rtcRoom = null;
        }
        RTCEngine.destroyRTCEngine();
    }
}