/**
* Function name: BytePlusRTC Quick Start
* Function simple description: Quickly run through ByteRTC audio & video call function
* Reminder:
* 1. Please follow the steps given on the interface to develop the audio & video call function
* 2. To demonstrate, all functional tokens are generated by the client side TokenGenerator class, please depend on the specific situation when actually accessing
*/


import UIKit
import SnapKit
import BytePlusRTC

@objc(QuickStartViewController)
class QuickStartViewController: BaseViewController, ByteRTCVideoDelegate, ByteRTCRoomDelegate {
    
    var rtcVideo: ByteRTCVideo?
    var rtcRoom: ByteRTCRoom?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.createUI()
        self.buildActions()
    }
    
    deinit {
        self.rtcRoom?.leaveRoom()
        self.rtcRoom?.destroy()
        self.rtcRoom = nil
        
        ByteRTCVideo.destroyRTCVideo()
        self.rtcVideo = nil
    }
    
    // MARK: Private method
    
    func buildActions() {
        stepButton1.buttonAction = { [weak self] in
            if self?.rtcVideo == nil {
                self?.rtcVideo = ByteRTCVideo.createRTCVideo(kAppID, delegate: self, parameters: [:])
            }
        }
        
        stepButton2.buttonAction = { [weak self] in
            if self?.rtcVideo != nil {
                self?.rtcVideo?.startVideoCapture()
                self?.rtcVideo?.startAudioCapture()
            }
        }
        
        stepButton3.buttonAction = { [weak self] in
            if self?.rtcVideo != nil {
                self?.bindLocalRenderView()
            }
        }
        
        stepButton4.buttonAction = { [weak self] in
            if self?.rtcVideo != nil {
                self?.joinRoom()
            }
        }
        
        stepButton6.buttonAction = { [weak self] in
            if self?.rtcRoom != nil {
                self?.rtcRoom?.leaveRoom()
            }
        }
        
        stepButton7.buttonAction = { [weak self] in
            if self?.rtcRoom != nil {
                self?.rtcRoom?.destroy()
                self?.rtcRoom = nil
            }
        }
        
        stepButton8.buttonAction = { [weak self] in
            self?.localView.userId = ""
            if self?.rtcVideo != nil {
                // Destroy engine
                ByteRTCVideo.destroyRTCVideo()
                self?.rtcVideo = nil
            }
        }
    }
    
    @objc func joinRoom()  {
        let roomId = self.roomTextField.text ?? ""
        let userId = self.userTextField.text ?? ""
        
        var vaild = checkValid(roomId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: LocalizedString("toast_check_valid_false"))
            return
        }
        
        vaild = checkValid(userId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: LocalizedString("toast_check_valid_false"))
            return
        }
        
        generatorToken(roomId: roomId, userId: userId) { [weak self] token in
            // Join room
            self?.rtcRoom = self?.rtcVideo?.createRTCRoom(roomId)
            self?.rtcRoom?.delegate = self
            
            let userInfo = ByteRTCUserInfo.init()
            userInfo.userId = userId
            
            let roomCfg = ByteRTCRoomConfig.init()
            roomCfg.isAutoPublish = true
            roomCfg.isAutoSubscribeAudio = true
            roomCfg.isAutoSubscribeVideo = true
            
            self?.rtcRoom?.joinRoom(token, userInfo: userInfo, roomConfig: roomCfg)
        }
    }
    
    func bindLocalRenderView() {
        // Set local rendering view
        let userId = self.userTextField.text ?? ""
        self.localView.userId = userId
        
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = self.localView.videoView
        canvas.renderMode = .hidden
        
        self.rtcVideo?.setLocalVideoCanvas(.main, withCanvas: canvas);
    }
    
    func bindRemoteRenderView(view: UserVideoView, roomId: String, userId: String) {
        // Set the remote user video rendering view
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = view.videoView
        canvas.renderMode = .hidden
        view.userId = userId
        
        let streamKey = ByteRTCRemoteStreamKey.init()
        streamKey.userId = userId
        streamKey.roomId = roomId;
        streamKey.streamIndex = .main
        
        self.rtcVideo?.setRemoteVideoCanvas(streamKey, withCanvas: canvas)
    }
    
    func removeRemoteRenderView(view: UserVideoView, roomId: String, userId: String) {
        // Remove the remote user's video rendering view
        let canvas = ByteRTCVideoCanvas.init()
        // View is set to empty
        canvas.view = nil
        canvas.renderMode = .hidden
        view.userId = ""
        
        let streamKey = ByteRTCRemoteStreamKey.init()
        streamKey.userId = userId
        streamKey.roomId = roomId;
        streamKey.streamIndex = .main
        
        self.rtcVideo?.setRemoteVideoCanvas(streamKey, withCanvas: canvas)
    }
    
    func createUI() -> Void {
        view.addSubview(containerView)
        self.containerView.addSubview(localView)
        self.containerView.addSubview(remoteView)
        
        containerView.snp.makeConstraints { make in
            make.top.equalTo(topView.snp.bottom)
            make.left.right.equalTo(self.view)
        }
        
        self.localView.snp.makeConstraints { make in
            make.left.top.equalTo(self.containerView)
            make.height.equalTo(self.containerView)
            make.width.equalTo(self.containerView).multipliedBy(0.5)
        }
        
        self.remoteView.snp.makeConstraints { make in
            make.right.bottom.equalTo(self.containerView)
            make.height.equalTo(self.containerView)
            make.width.equalTo(self.containerView).multipliedBy(0.5)
        }
        
        view.addSubview(roomTextField)
        view.addSubview(userTextField)
        view.addSubview(stepButton1)
        view.addSubview(stepButton2)
        view.addSubview(stepButton3)
        view.addSubview(stepButton4)
        view.addSubview(stepLabel5)
        view.addSubview(stepButton6)
        view.addSubview(stepButton7)
        view.addSubview(stepButton8)
        
        roomTextField.snp.makeConstraints { make in
            make.left.equalToSuperview().offset(10)
            make.height.equalTo(32)
            make.top.lessThanOrEqualTo(containerView.snp.bottom).offset(10)
        }
        
        userTextField.snp.makeConstraints { make in
            make.centerY.equalTo(roomTextField)
            make.left.equalTo(roomTextField.snp.right).offset(20)
            make.right.equalToSuperview().offset(-10)
            make.width.equalTo(roomTextField)
            make.height.equalTo(32)
        }
        
        stepButton1.snp.makeConstraints { make in
            make.top.equalTo(roomTextField.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton2.snp.makeConstraints { make in
            make.top.equalTo(stepButton1.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton3.snp.makeConstraints { make in
            make.top.equalTo(stepButton2.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton4.snp.makeConstraints { make in
            make.top.equalTo(stepButton3.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepLabel5.snp.makeConstraints { make in
            make.height.equalTo(stepButton4)
            make.top.equalTo(stepButton4.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
        }
        
        stepButton6.snp.makeConstraints { make in
            make.top.equalTo(stepLabel5.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton7.snp.makeConstraints { make in
            make.top.equalTo(stepButton6.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton8.snp.makeConstraints { make in
            make.top.equalTo(stepButton7.snp.bottom).offset(10)
            make.bottom.equalTo(self.view.safeAreaLayoutGuide.snp.bottom).offset(-10)
            make.left.right.equalToSuperview()
        }
    }
    
    // MARK: lazyload
    lazy var roomTextField: UITextField = {
        let textField = UITextField()
        textField.placeholder = LocalizedString("hint_room_id")
        textField.borderStyle = .roundedRect
        return textField
    }()
    
    lazy var userTextField: UITextField = {
        let textField = UITextField()
        textField.placeholder = LocalizedString("hint_user_id")
        textField.borderStyle = .roundedRect
        return textField
    }()
    
    lazy var stepButton1: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_1_create_engine"), buttonText: LocalizedString("button_create_engine"))
        
        return stepButton
    }()
    
    lazy var stepButton2: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_2_start_capture"), buttonText: LocalizedString("button_start_capture"))
        
        return stepButton
    }()
    lazy var stepButton3: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_3_set_local_canvas"), buttonText: LocalizedString("button_set_local_canvas"))
        
        return stepButton
    }()
    
    lazy var stepButton4: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_4_join_room"), buttonText: LocalizedString("button_join_room"))
        
        return stepButton
    }()
    
    lazy var stepLabel5: UILabel = {
        let label = UILabel.init()
        label.textAlignment = .center
        label.font = UIFont.systemFont(ofSize: 14)
        label.text = LocalizedString("label_step_5_set_remote_canvas")
        return label
    }()
    
    lazy var stepButton6: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_6_leave_room"), buttonText: LocalizedString("button_leave_room"))
        
        return stepButton
    }()
    lazy var stepButton7: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_7_destroy_room"), buttonText: LocalizedString("button_destroy_room"))
        
        return stepButton
    }()
    lazy var stepButton8: StepButton = {
        let stepButton = StepButton.init(labelText: LocalizedString("label_step_8_destroy_engine"), buttonText: LocalizedString("button_destroy_engine"))
        
        return stepButton
    }()
    
    lazy var containerView: UIView = {
        let view = UIView.init()
        view.backgroundColor = .groupTableViewBackground
        return view
    }()
    
    lazy var localView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    lazy var remoteView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    // MARK: ByteRTCVideoDelegate & ByteRTCRoomDelegate
    // Room entry status
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onRoomStateChanged roomId: String, withUid uid: String, state: Int, extraInfo: String) {
        ToastComponents.shared.show(withMessage: "onRoomStateChanged uid: \(uid) state:\(state)")
        
        if state == 0 {
            print("Join Room Success")
        }
    }

    // Remote user publishing stream
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserPublishStream userId: String, type: ByteRTCMediaStreamType) {
        ToastComponents.shared.show(withMessage: "onUserPublishStream uid: \(userId)")
        // Render remote users
        if type == .video || type == .both {
            DispatchQueue.main.async {
                self.bindRemoteRenderView(view: self.remoteView, roomId: rtcRoom.getId(), userId: userId)
            }
        }
    }
    
    // Remote user cancels publishing flow
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserUnpublishStream userId: String, type: ByteRTCMediaStreamType, reason: ByteRTCStreamRemoveReason) {
        ToastComponents.shared.show(withMessage: "onUserUnpublishStream uid: \(userId)")
        
        if type == .video || type == .both {
            // Remove UI display
            DispatchQueue.main.async {
                if userId == self.remoteView.userId {
                    self.removeRemoteRenderView(view: self.remoteView, roomId: rtcRoom.getId(), userId: userId)
                }
            }
        }
    }
    
    // Remote users join the room
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserJoined userInfo: ByteRTCUserInfo, elapsed: Int) {
        ToastComponents.shared.show(withMessage: "onUserJoined uid: \(userInfo.userId)")
    }
    
    // The remote user leaves the room
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserLeave uid: String, reason: ByteRTCUserOfflineReason) {
        ToastComponents.shared.show(withMessage: "onUserLeave uid: \(uid)")
    }
    
    func onTokenWillExpire(_ rtcRoom: ByteRTCRoom) {
        // Token is about to expire
        ToastComponents.shared.show(withMessage: LocalizedString("toast_will_expire"))
    }
}
