/**
* Function name: BytePlusRTC video common configuration
* Simple description of the function: modify the commonly used capture and encoding parameters of the video, set the rotation angle, watermark and other functions
* Reminder:
* 1. To demonstrate, all functional tokens are generated by the client side TokenGenerator class, please depend on the specific situation when actually accessing
* Reference document: https://docs.byteplus.com/en/docs/byteplus-rtc/docs-70122
*/


import UIKit
import SnapKit
import BytePlusRTC

@objc(CommonVideoConfigViewController)
class CommonVideoConfigViewController: BaseViewController, ByteRTCVideoDelegate, ByteRTCRoomDelegate {
    
    var rtcVideo: ByteRTCVideo?
    var rtcRoom: ByteRTCRoom?
    var captureConfig: ByteRTCVideoCaptureConfig?
    var encoderCfg : ByteRTCVideoEncoderConfig?
    
    var users : Array = Array<ByteRTCRemoteStreamKey>()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.createUI()
        self.buildRTCEngine()
        self.buildActions()
    }
    
    deinit {
        
        self.rtcRoom?.leaveRoom()
        self.rtcRoom?.destroy()
        self.rtcRoom = nil
        
        ByteRTCVideo.destroyRTCVideo()
        self.rtcVideo = nil
    }
    
    // MARK: Private method
    
    @objc func joinRoom()  {
        let roomId = self.roomSettingItem.text ?? ""
        let userId = self.userSettingItem.text ?? ""
        
        var vaild = checkValid(roomId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: LocalizedString("toast_check_valid_false"))
            return
        }
        
        vaild = checkValid(userId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: LocalizedString("toast_check_valid_false"))
            return
        }
        
        joinButton.isSelected = !joinButton.isSelected
        
        if joinButton.isSelected {
            generatorToken(roomId: roomId, userId: userId) { [weak self] token in
                self?.joinButton.setTitle(LocalizedString("button_leave_room"), for: .normal)
                // Join room
                self?.rtcRoom = self?.rtcVideo?.createRTCRoom(roomId)
                self?.rtcRoom?.delegate = self
                
                let userInfo = ByteRTCUserInfo.init()
                userInfo.userId = userId
                
                let roomCfg = ByteRTCRoomConfig.init()
                roomCfg.isAutoPublish = true
                roomCfg.isAutoSubscribeAudio = true
                roomCfg.isAutoSubscribeVideo = true
                
                self?.rtcRoom?.joinRoom(token, userInfo: userInfo, roomConfig: roomCfg)
            }
        }
        else {
            self.joinButton.setTitle(LocalizedString("button_join_room"), for: .normal)
            self.rtcRoom?.leaveRoom()
        }
    }
    
    @objc func scrollViewAction()  {
        self.view.endEditing(true)
    }
    
    func buildRTCEngine() {
        // Create engine
        self.rtcVideo = ByteRTCVideo.createRTCVideo(kAppID, delegate: self, parameters: [:])
        
        // Set video capture parameters
        let config = ByteRTCVideoCaptureConfig.init()
        config.preference = .mannal
        config.videoSize = CGSize(width: 480, height: 640)
        config.frameRate = 15
        self.captureConfig = config;
        self.rtcVideo?.setVideoCaptureConfig(config)
        
        // Set video publishing parameters
        let encoderCfg = ByteRTCVideoEncoderConfig.init()
        encoderCfg.width = 480
        encoderCfg.height = 640
        encoderCfg.frameRate = 15
        encoderCfg.maxBitrate = 1000
        self.encoderCfg = encoderCfg
        self.rtcVideo?.setMaxVideoEncoderConfig(encoderCfg)
        
        // Enable local audio and video collection
        self.rtcVideo?.startVideoCapture()
        self.rtcVideo?.startAudioCapture()
        
        self.bindLocalRenderView()
    }
    
    func bindLocalRenderView() {
        // Set local rendering view
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = self.localView.videoView
        canvas.renderMode = .hidden
        self.localView.userId = userSettingItem.text ?? ""
        
        self.rtcVideo?.setLocalVideoMirrorType(.none)
        self.rtcVideo?.setLocalVideoCanvas(.main, withCanvas: canvas);
    }
    
    func updateRenderView() {
        // Get the first user of the room
        var remoteUser:ByteRTCRemoteStreamKey?
        
        for streamKey in self.users {
            if remoteUser == nil && streamKey.roomId ==  self.roomSettingItem.text {
                remoteUser = streamKey
            }
        }
        
        if (remoteUser != nil) {
            self.bindRemoteRenderView(view: self.firstRemoteView,roomId: (remoteUser?.roomId)!,userId: (remoteUser?.userId)!)
        }
    }
    
    func buildActions() {
        weak var weakSelf = self
        
        // Set acquisition resolution
        self.resolutionSheetView.didSelectOption = {(value) in
            var videoSize:CGSize?
            
            switch value {
            case 0:
                videoSize = CGSizeMake(480, 640)
            case 1:
                videoSize = CGSizeMake(720, 1280)
            case 2:
                videoSize = CGSizeMake(1080, 1920)
            default:
                videoSize = CGSizeMake(480, 640)
            }
            
            weakSelf?.captureConfig?.videoSize = videoSize!
            
            weakSelf?.rtcVideo?.setVideoCaptureConfig(weakSelf?.captureConfig)
        }
        
        // Set collection preferences
        self.captureModeSheetView.didSelectOption = {(value) in
            
            switch value {
            case 0:
                weakSelf?.captureConfig?.preference = .auto
            case 1:
                weakSelf?.captureConfig?.preference = .mannal
            case 2:
                weakSelf?.captureConfig?.preference = .autoPerformance
            default:
                weakSelf?.captureConfig?.preference = .auto
            }
            
            weakSelf?.rtcVideo?.setVideoCaptureConfig(weakSelf?.captureConfig)
        }
        
        // Set acquisition frame rate
        self.captureFpsSheetView.didSelectOption = {(value) in
            
            switch value {
            case 0:
                weakSelf?.captureConfig?.frameRate = 15
            case 1:
                weakSelf?.captureConfig?.frameRate = 30
            case 2:
                weakSelf?.captureConfig?.frameRate = 60
            default:
                weakSelf?.captureConfig?.frameRate = 15
            }
            
            weakSelf?.rtcVideo?.setVideoCaptureConfig(weakSelf?.captureConfig)
        }
        
        // Set encoding resolution
        self.encoderResolutionSheetView.didSelectOption = {(value) in
            
            switch value {
            case 0:
                weakSelf?.encoderCfg?.width = 480
                weakSelf?.encoderCfg?.height = 640
            case 1:
                weakSelf?.encoderCfg?.width = 720
                weakSelf?.encoderCfg?.height = 1280
            case 2:
                weakSelf?.encoderCfg?.width = 1080
                weakSelf?.encoderCfg?.height = 1920
            default:
                weakSelf?.encoderCfg?.width = 480
                weakSelf?.encoderCfg?.height = 640
            }
            
            weakSelf?.rtcVideo?.setMaxVideoEncoderConfig(weakSelf?.encoderCfg)
        }
        
        // Set encoding frame rate
        self.fpsSheetView.didSelectOption = {(value) in
            
            switch value {
            case 0:
                weakSelf?.encoderCfg?.frameRate = 15
            case 1:
                weakSelf?.encoderCfg?.frameRate = 30
            case 2:
                weakSelf?.encoderCfg?.frameRate = 60
            default:
                weakSelf?.encoderCfg?.frameRate = 15
            }
                        
            weakSelf?.rtcVideo?.setMaxVideoEncoderConfig(weakSelf?.encoderCfg)
        }
        
        // Set the maximum bit rate
        self.maxBitrateSettingItem.onValueChanged = {(value) in
            guard let intValue = Int(value) else {
                return
            }
            weakSelf?.encoderCfg?.maxBitrate = intValue
            weakSelf?.rtcVideo?.setMaxVideoEncoderConfig(weakSelf?.encoderCfg)
        }
        
        // Set the maximum bit rate
        self.minBitrateSettingItem.onValueChanged = {(value) in
            guard let intValue = Int(value) else {
                return
            }
            weakSelf?.encoderCfg?.minBitrate = intValue
            weakSelf?.rtcVideo?.setMaxVideoEncoderConfig(weakSelf?.encoderCfg)
        }
        
        // Set encoding policy preferences
        self.encodePrefrenceSheetView.didSelectOption = {(value) in
            weakSelf?.encoderCfg?.encoderPreference = ByteRTCVideoEncoderPreference(rawValue: value)!
            weakSelf?.rtcVideo?.setMaxVideoEncoderConfig(weakSelf?.encoderCfg)
        }
        
        // Set local rendering fill mode
        self.localRenderModeSheetView.didSelectOption = {(value) in
            weakSelf?.rtcVideo?.updateLocalVideoCanvas(.main, withRenderMode: ByteRTCRenderMode(rawValue: UInt(value)+1)!, withBackgroundColor: 0xffffff)
        }
        
        // Set local video mirroring mode
        self.localMirrorModeSheetView.didSelectOption = {(value) in
            var mirrorType:ByteRTCMirrorType?
            switch value {
            case 0:
                mirrorType = ByteRTCMirrorType.none
            case 1:
                mirrorType = ByteRTCMirrorType.render
            case 2:
                mirrorType = ByteRTCMirrorType.renderAndEncoder
            default:
                mirrorType = ByteRTCMirrorType.none
            }
            
            weakSelf?.rtcVideo?.setLocalVideoMirrorType(mirrorType!)
        }
        
        // Set remote rendering fill mode
        self.remoteRenderModeSheetView.didSelectOption = {[weak self] value in
            weak var weakSelf = self

            var remoteUser:ByteRTCRemoteStreamKey?
            
            if let users = self?.users {
                for streamKey in users {
                    if remoteUser == nil && streamKey.roomId == self?.roomSettingItem.text {
                        remoteUser = streamKey
                    }
                }
            }
            
            if (remoteUser != nil) {
                weakSelf?.rtcVideo?.updateRemoteStreamVideoCanvas(remoteUser!, withRenderMode:  ByteRTCRenderMode(rawValue: UInt(value)+1)!, withBackgroundColor: 0xffffff)
            }
        }
    }
    
    func bindRemoteRenderView(view: UserVideoView, roomId: String, userId: String) {
        // Set the remote user video rendering view
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = view.videoView
         canvas.renderMode = .hidden
        view.userId = userId
        
        let streamKey = ByteRTCRemoteStreamKey.init()
        streamKey.userId = userId
        streamKey.roomId = roomId;
        streamKey.streamIndex = .main
        
        self.rtcVideo?.setRemoteVideoCanvas(streamKey, withCanvas: canvas)
    }
    
    func createUI() -> Void {
        self.view.addSubview(scrollView)
        scrollView.snp.makeConstraints { make in
            make.top.equalTo(topView.snp.bottom)
            make.left.right.bottom.equalToSuperview()
        }
        
        let view = UIView()
        scrollView.addSubview(view)
        
        view.snp.makeConstraints { make in
            make.edges.equalToSuperview()
            make.width.equalToSuperview()
        }

        view.addSubview(containerView)
        containerView.snp.makeConstraints { make in
            make.top.left.right.equalToSuperview()
            make.height.equalTo(scrollView).multipliedBy(0.4)
        }
        
        containerView.addSubview(localView)
        containerView.addSubview(firstRemoteView)
        
        localView.snp.makeConstraints { make in
            make.left.top.equalTo(self.containerView)
            make.width.equalTo(self.containerView).multipliedBy(0.5)
            make.height.equalTo(self.containerView)
        }
        
        firstRemoteView.snp.makeConstraints { make in
            make.right.top.equalTo(self.containerView)
            make.width.equalTo(self.containerView).multipliedBy(0.5)
            make.height.equalTo(self.containerView)        }
        
        view.addSubview(roomSettingItem)
        view.addSubview(userSettingItem)
        view.addSubview(joinButton)
        
        roomSettingItem.snp.makeConstraints { make in
            make.top.equalTo(containerView.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.height.equalTo(30)
        }
        
        userSettingItem.snp.makeConstraints { make in
            make.centerY.equalTo(roomSettingItem)
            make.left.equalTo(roomSettingItem.snp.right).offset(20)
            make.right.equalToSuperview().offset(-10)
            make.width.height.equalTo(roomSettingItem)
        }
        
        joinButton.snp.makeConstraints { make in
            make.top.equalTo(roomSettingItem.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
            make.height.equalTo(36)
        }
        
        view.addSubview(renderLabel)
        renderLabel.snp.makeConstraints { make in
            make.top.equalTo(joinButton.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        view.addSubview(localRenderModeSheetView)
        view.addSubview(remoteRenderModeSheetView)
        view.addSubview(localMirrorModeSheetView)
        
        localRenderModeSheetView.snp.makeConstraints { make in
            make.top.equalTo(renderLabel.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
            
        }

        remoteRenderModeSheetView.snp.makeConstraints { make in
            make.top.equalTo(localRenderModeSheetView.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        localMirrorModeSheetView.snp.makeConstraints { make in
            make.top.equalTo(remoteRenderModeSheetView.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        
        view.addSubview(captureLabel)
        captureLabel.snp.makeConstraints { make in
            make.top.equalTo(localMirrorModeSheetView.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }

        view.addSubview(resolutionSheetView)
        view.addSubview(captureModeSheetView)
        view.addSubview(captureFpsSheetView)
        
        resolutionSheetView.snp.makeConstraints { make in
            make.top.equalTo(captureLabel.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        captureModeSheetView.snp.makeConstraints { make in
            make.top.equalTo(resolutionSheetView.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        captureFpsSheetView.snp.makeConstraints { make in
            make.top.equalTo(captureModeSheetView.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        view.addSubview(encodeLabel)
        encodeLabel.snp.makeConstraints { make in
            make.top.equalTo(captureFpsSheetView.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
        }
        
        view.addSubview(encoderResolutionSheetView)
        encoderResolutionSheetView.snp.makeConstraints { make in
            make.top.equalTo(encodeLabel.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        view.addSubview(fpsSheetView)
        fpsSheetView.snp.makeConstraints { make in
            make.top.equalTo(encoderResolutionSheetView.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        view.addSubview(maxBitrateSettingItem)
        maxBitrateSettingItem.snp.makeConstraints { make in
            make.top.equalTo(fpsSheetView.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
        }
        
        view.addSubview(minBitrateSettingItem)
        minBitrateSettingItem.snp.makeConstraints { make in
            make.top.equalTo(maxBitrateSettingItem.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
        }
        
        view.addSubview(encodePrefrenceSheetView)
        encodePrefrenceSheetView.snp.makeConstraints { make in
            make.top.equalTo(minBitrateSettingItem.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
            make.bottom.equalToSuperview().offset(-10)
        }
        
    }
    
    // MARK: Lazy laod
    lazy var scrollView: UIScrollView = {
        let scrollView = UIScrollView()
        scrollView.showsVerticalScrollIndicator = false
        scrollView.isUserInteractionEnabled = true
        let tap = UITapGestureRecognizer(target: self, action: #selector(scrollViewAction))
        scrollView.addGestureRecognizer(tap)
        return scrollView
    }()
    
    lazy var roomSettingItem: TextFieldView = {
        let settingView = TextFieldView()
        settingView.title = LocalizedString("hint_room_id")
        return settingView
    }()
    
    lazy var userSettingItem: TextFieldView = {
        let settingView = TextFieldView()
        settingView.title = LocalizedString("hint_user_id")
        return settingView
    }()
    
    lazy var joinButton: UIButton = {
        let button = BaseButton()
        button.setTitle(LocalizedString("button_join_room"), for: .normal)
        button.addTarget(self, action: #selector(joinRoom), for: .touchUpInside)
        return button
    }()
    
    lazy var containerView: UIView = {
        let view = UIView.init()
        view.backgroundColor = .groupTableViewBackground
        return view
    }()
    
    lazy var renderLabel: UILabel = {
        let label = UILabel()
        label.text = LocalizedString("label_render_settings")
        label.font = UIFont.boldSystemFont(ofSize: 18)
        return label
    }()
    
    lazy var captureLabel: UILabel = {
        let label = UILabel()
        label.text = LocalizedString("button_update_capture_config")
        label.font = renderLabel.font
        return label
    }()
    
    lazy var resolutionSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_capture_resolution"), optionArray: ["640*480","1280*720","1920*1080"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var captureModeSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_capture_preference"), optionArray: ["Auto","mannal","autoPerformance"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var captureFpsSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_capture_frame_rate"), optionArray: ["15","30","60"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var encoderResolutionSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_encode_resolution"), optionArray: ["640*480","1280*720","1920*1080"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var encodeLabel: UILabel = {
        let label = UILabel()
        label.text = LocalizedString("label_encode_settings")
        label.font = renderLabel.font
        return label
    }()
    
    lazy var fpsSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_encode_frame_rate"), optionArray: ["15","30","60"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var maxBitrateSettingItem: SettingItemView = {
        let settingView = SettingItemView()
        settingView.title = LocalizedString("label_max_bitrate")
        return settingView
    }()
    
    lazy var minBitrateSettingItem: SettingItemView = {
        let settingView = SettingItemView()
        settingView.title = LocalizedString("label_min_bitrate")
        return settingView
    }()
    
    lazy var encodePrefrenceSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_encoder_preference"), optionArray: ["Disable","MaintainFramerate","MaintainQuality","Balance"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var localRenderModeSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_local_render_mode"), optionArray: ["Hidden","Fit","Fill"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var localMirrorModeSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_local_mirror_type"), optionArray: ["None","Render","RenderAndEncoder"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var remoteRenderModeSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_remote_render_mode"), optionArray: ["Hidden","Fit","Fill"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var localView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    lazy var firstRemoteView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    // MARK: ByteRTCVideoDelegate & ByteRTCRoomDelegate
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onRoomStateChanged roomId: String, withUid uid: String, state: Int, extraInfo: String) {
        ToastComponents.shared.show(withMessage: "onRoomStateChanged uid: \(uid) state:\(state)")
        
    }
    
    // Remote user publishing stream
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserPublishStream userId: String, type: ByteRTCMediaStreamType) {
        ToastComponents.shared.show(withMessage: "onUserPublishStream uid: \(userId)")
        
        if type == .video || type == .both {
            
            let streamKey = ByteRTCRemoteStreamKey.init()
            streamKey.userId = userId
            streamKey.roomId = rtcRoom.getId();
            streamKey.streamIndex = .main
            
            self.users.append(streamKey)
            
            DispatchQueue.main.async {
                self.updateRenderView()
            }
        }
    }
    
    // Remote user cancels publishing flow
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserUnpublishStream userId: String, type: ByteRTCMediaStreamType, reason: ByteRTCStreamRemoveReason) {
        ToastComponents.shared.show(withMessage: "onUserUnpublishStream uid: \(userId)")
        
        if type == .video || type == .both {
            
            // Remove from self.users
            var itemsToRemove: [ByteRTCRemoteStreamKey] = []
            
            for streamKey in self.users {
                if streamKey.userId == userId {
                    itemsToRemove.append(streamKey)
                }
            }
            
            for item in itemsToRemove {
                if let index = self.users.firstIndex(of: item) {
                    self.users.remove(at: index)
                }
            }
            
            DispatchQueue.main.async {
                for videoView in self.containerView.subviews {
                    if let view = videoView as? UserVideoView {
                        
                        let userId = view.userId
                        
                        if userId == userId {
                            view.userId = ""
                        }
                    }
                }
            }
            
            DispatchQueue.main.async {
                self.updateRenderView()
            }
        }
        
    }
    
    // Callback when local video size or direction changes
    func rtcEngine(_ engine: ByteRTCVideo, onLocalVideoSizeChanged streamIndex: ByteRTCStreamIndex, withFrameInfo frameInfo: ByteRTCVideoFrameInfo) {
        ToastComponents.shared.show(withMessage: "onLocalVideoSizeChanged width: \(frameInfo.width) height: \(frameInfo.height) rotation: \(frameInfo.rotation)")
    }
    
    // Remote users join the room
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserJoined userInfo: ByteRTCUserInfo, elapsed: Int) {
        ToastComponents.shared.show(withMessage: "onUserJoined uid: \(userInfo.userId)")
        
    }
    
    // The remote user leaves the room
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserLeave uid: String, reason: ByteRTCUserOfflineReason) {
        ToastComponents.shared.show(withMessage: "onUserLeave uid: \(uid)")
        
    }
}

