plugins {
    id 'com.android.library'
}

android {
    namespace "com.byteplus.live.pusher"
    compileSdk project.compileSdkVersion

    defaultConfig {
        minSdkVersion project.minSdkVersion
        targetSdkVersion project.targetSdkVersion

        consumerProguardFiles "consumer-rules.pro"

        buildConfigField('String', 'APP_ID', "\"${safeGetProp('APP_ID')}\"")
        buildConfigField('String', 'APP_KEY', "\"${safeGetProp('APP_KEY')}\"")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(project.javaLanguageVersion)
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.bundles.viewmodel

    implementation project(':component:solution-base')
    implementation project(':component:effectkit')
    implementation project(':solutions:media-live:live-common')

    implementation libs.rtc.sdk

    implementation libs.zxing

    implementation project(':solutions:rtc-api-example:rtc-api-example-base')
}

def safeGetProp(prop, defaultValue = '') {
    if (rootProject.hasProperty(prop)) {
        return rootProject.property(prop)
    } else if (project.hasProperty(prop)) {
        return project.property(prop)
    } else {
        return defaultValue
    }
}
