# for VOD
-keep class com.ss.ttm.** { *; }
-keep class com.ss.ttvideoengine.** { *; }
-keep class com.ss.mediakit.** { *; }
-keep class com.ss.texturerender.** { *; }
-keep class com.bytedance.** { *; }
-keep class com.pandora.ttlicense2.** { *; }
-keep class com.pandora.common.applog.** { *; }
-keep class com.pandora.vod.VodSDK { *; }
-keep class com.bytertc.volcbaselog.VolcBaseLogConfig { *; }
-keep class com.bytertc.volcbaselog.VolcBaseLogNative { *; }