source 'https://cdn.cocoapods.org/'
source 'https://github.com/byteplus-sdk/byteplus-specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '13.0'
install! 'cocoapods',
:deterministic_uuids => false,
:disable_input_output_paths => true


# TTSDK version
$TT_SDK_VERSION = '1.43.300.2-premium'

$RTC_SDK = 'TTSDKFramework/RTCSDK'
def rtc_pods
  pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['RTCSDK'], :modular_headers => true
end

def common_pods
  pod 'AFNetworking', '~> 4.0'
  pod 'SDWebImage', '~> 5.12.0'
  # app entry
  pod 'App', :path => './Component/App'
  # Basic Component
  pod 'AppConfig', :path => './Component/AppConfig'
  pod 'ToolKit', :path => './Component/ToolKit'
  # Login Kit
  pod 'LoginKit', :path => './Component/LoginKit'
end

def scene_InteractiveLive_pods
  # Interactive Live
  pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['LivePull-RTS', 'LivePush-RTS', 'RTCSDK']
  pod 'InteractiveLive', :path => './Component/InteractiveLive'
  # Effect
  pod 'EffectResources', :path => './Component/Effects/EffectResources'
  pod 'EffectUIKit', :path => './Component/Effects/EffectUIKit'
  pod 'BytedEffectSDK', :path => './Component/Effects/BytedEffectSDK'
  pod 'AllEffectKit', :path => './Component/Effects/AllEffectKit', :subspecs => ['RTCEffectManager']  
end

def scene_VideoPlaybackEdit_pods
  # One-Stop Video
  pod 'VideoPlaybackEdit', :path => './Component/VideoPlaybackEdit'
  pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['Player']
end

def scene_Vod_SingleFunction_pods
  # One-Stop Video
  pod 'VodSingleFunction', :path => './Component/VodSingleFunction'
  pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['Player']
end

def scene_KTV_pods
  # One-Stop Video
  rtc_pods
  pod 'KTV', :path => './Component/KTV'
  pod 'Chorus', :path => './Component/Chorus'
end

def scene_MediaLive_pods
  # LiveDemo SingleFunction
  pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['LivePull-RTS', 'LivePush-RTS', 'Quic/Pull', 'Quic/Push', 'ScreenCapture']
  pod 'MediaLive', :path => './Component/MediaLive'
  # Effect
  pod 'EffectResources', :path => './Component/Effects/EffectResources'
  pod 'EffectUIKit', :path => './Component/Effects/EffectUIKit'
  pod 'BytedEffectSDK', :path => './Component/Effects/BytedEffectSDK'
  pod 'AllEffectKit', :path => './Component/Effects/AllEffectKit', :subspecs => ['LiveEffectManager']  
end

def develop_rtc_pods
  pod 'ApiExampleEntry', :path => 'component/ApiExampleEntry'
  pod 'RTCDependency', :path => 'component/RTCDependency', :subspecs=> ['audioeffect', 'ScreenCapture']
  pod 'RTCAPIExample', :path => 'Component/RTCAPIExample'
  pod 'RTCTokenOnlineKit', :path => 'Component/RTCTokenOnlineKit'
  
  # Effect
  pod 'EffectResources', :path => './Component/Effects/EffectResources'
  pod 'BytedEffectSDK', :path => './Component/Effects/BytedEffectSDK'
  rtc_pods
  pod 'SnapKit', '~> 5.6.0'
  pod 'OpenSSL-Universal', '~> 1.0.2.17'
  pod 'IQKeyboardManagerSwift', '~> 6.5.4'
end


def scene_TTProtoTypeRoom_pods
    pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['LivePull-RTS', 'Player', 'RTCSDK']
    pod 'TTProtoTypeRoom', :path => './Component/TTProtoTypeRoom'
end

def scene_MiniDrama_pods
  pod 'TTSDKFramework', $TT_SDK_VERSION, :subspecs => ['Player']
  pod 'MiniDrama', :path => './Component/MiniDrama'
end

def scene_AIChat_pods
  rtc_pods
  pod 'AIChat', :path => './Component/AIChat'
end

target 'VideoOne' do
  common_pods
  scene_InteractiveLive_pods
  scene_KTV_pods
  scene_VideoPlaybackEdit_pods
  scene_Vod_SingleFunction_pods
  scene_MediaLive_pods
  develop_rtc_pods
  scene_TTProtoTypeRoom_pods
  scene_MiniDrama_pods
  scene_AIChat_pods
  
end

target 'ScreenShareExtension' do
  pod 'AppConfig', :path => './Component/AppConfig'
  pod 'TTSDKFramework',$TT_SDK_VERSION, :subspecs => ['ScreenCaptureExtension']
  pod 'RTCDependency', :path => 'component/RTCDependency', :subspecs=> ['audioeffect', 'ScreenCapture']
end

post_install do |installer|
  [installer.generated_projects || [], installer.pods_project || []].
  flatten.map { |p| p.targets }.
  flatten.each do |target|
    target.build_configurations.each do |config|
      
      # Fix bundle targets Signing
      if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
        config.build_settings['CODE_SIGN_IDENTITY'] = '-'
        config.build_settings['CODE_SIGN_ENTITLEMENTS'] = '-'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      end
    end
  end
end
