source 'https://cdn.cocoapods.org/'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '11.0'
install! 'cocoapods',
         :deterministic_uuids => false,
         :disable_input_output_paths => true

target 'VideoOne' do
  # TTSDK and RTC SDK
  pod 'TTSDK', '1.37.200.5-premium', :subspecs => %w[LivePull-RTS LivePush-RTS]

  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'MJRefresh'
  pod 'AFNetworking', '~> 4.0'
  # app entry
  pod 'App', :path => './Component/App'
  # Basic Component
  pod 'ToolKit', :path => './Component/ToolKit'
  # Login Kit
   pod 'LoginKit', :path => './Component/LoginKit'
  # Live Demo
  pod 'LiveDemo', :path => './Component/LiveDemo'
end

post_install do |installer|
  [installer.generated_projects || [], installer.pods_project || []].
    flatten.map { |p| p.targets }.
    flatten.each do |target|
    # Fix bundle targets Signing
    if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGN_IDENTITY'] = '-'
        config.build_settings['CODE_SIGN_ENTITLEMENTS'] = '-'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      end
    end
  end
end
