/**
* Function name: BytePlusRTC Bel Canto and Sound Effects
* Function brief description: This function shows reverb, noise reduction and other functions
* Reminder:
* 1. This demo demonstrates the function of Bel Canto and sound effects, demonstrating various sound processing special effects. Please consult a technician before using this function
* 2. To demonstrate, all functional tokens are generated by the client side TokenGenerator class, please depend on the specific situation when actually accessing
* Reference document: https://docs.byteplus.com/en/docs/byteplus-rtc/docs-1178327
*/

import UIKit
import SnapKit
import BytePlusRTC

@objc(SoundEffectsViewController)
class SoundEffectsViewController: BaseViewController, ByteRTCVideoDelegate, ByteRTCRoomDelegate {
    var rtcVideo: ByteRTCVideo?
    var rtcRoom: ByteRTCRoom?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.createUI()
        self.buildRTCEngine()
        self.buildActions()
    }
    
    deinit {
        self.rtcRoom?.leaveRoom()
        self.rtcRoom?.destroy()
        self.rtcRoom = nil
        
        ByteRTCVideo.destroyRTCVideo()
        self.rtcVideo = nil
    }
    
    // MARK: Private method
    @objc func joinRoom()  {
        let roomId = self.roomSettingItem.text ?? ""
        let userId = self.userSettingItem.text ?? ""
        
        var vaild = checkValid(roomId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: LocalizedString("toast_check_valid_false"))
            return
        }
        
        vaild = checkValid(userId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: LocalizedString("toast_check_valid_false"))
            return
        }
        
        joinButton.isSelected = !joinButton.isSelected
        
        if joinButton.isSelected {
            generatorToken(roomId: roomId, userId: userId) { [weak self] token in
                self?.joinButton.setTitle(LocalizedString("button_leave_room"), for: .normal)
                
                // Join room
                self?.rtcRoom = self?.rtcVideo?.createRTCRoom(roomId)
                self?.rtcRoom?.delegate = self
                
                let userInfo = ByteRTCUserInfo.init()
                userInfo.userId = userId
                
                let roomCfg = ByteRTCRoomConfig.init()
                roomCfg.isAutoPublish = true
                roomCfg.isAutoSubscribeAudio = true
                roomCfg.isAutoSubscribeVideo = true
                
                self?.rtcRoom?.joinRoom(token, userInfo: userInfo, roomConfig: roomCfg)
            }
        }
        else {
            self.joinButton.setTitle(LocalizedString("button_join_room"), for: .normal)
            self.rtcRoom?.leaveRoom()
        }
        
    }
    
    func buildRTCEngine() {
        // Create engine
        self.rtcVideo = ByteRTCVideo.createRTCVideo(kAppID, delegate: self, parameters: [:])
        
        // Enable local audio and video collection
        self.rtcVideo?.startVideoCapture()
        self.rtcVideo?.startAudioCapture()
        
        self.bindLocalRenderView()
    }
    
    func bindLocalRenderView() {
        // Set local rendering view
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = self.localView.videoView
        canvas.renderMode = .hidden
        self.localView.userId = userSettingItem.text ?? ""
        
        self.rtcVideo?.setLocalVideoCanvas(.main, withCanvas: canvas);
    }
    
    func buildActions() {
        weak var weakSelf = self
        
        // Reverberation
        self.voiceReverbSheetView.didSelectOption = {(value) in
            weakSelf?.rtcVideo?.setVoiceReverbType(ByteRTCVoiceReverbType(rawValue: Int(value))!)
        }
        
        // Transpose
        self.pitchSetting.onValueChanged = {(value) in
            weakSelf?.rtcVideo?.setLocalVoicePitch(Int(value))
        }
        
        // Voice ans
        self.voiceAnsSheetView.didSelectOption = {(value) in
            weakSelf?.rtcVideo?.setAnsMode(ByteRTCAnsMode(rawValue: Int(value))!)
        }
    }
    
    @objc func modifyReverbConfig() {
        self.rtcVideo?.enableLocalVoiceReverb(true)
        
        let config = ByteRTCVoiceReverbConfig.init()
        config.roomSize = Float(self.roomSizeSetting.valueLabel.text!)!
        config.decayTime = Float(self.decayTimeSetting.valueLabel.text!)!
        config.damping = Float(self.dampingSetting.valueLabel.text!)!
        config.wetGain = Float(self.wetGainSetting.valueLabel.text!)!
        config.dryGain = Float(self.dryGainSetting.valueLabel.text!)!
        config.preDelay = Float(self.preDelaySetting.valueLabel.text!)!
        
        self.rtcVideo?.setLocalVoiceReverbParam(config)
    }
    
    @objc func scrollViewAction()  {
        self.view.endEditing(true)
    }
    
    func createUI() -> Void {
        
        // ScrollView
        self.view.addSubview(scrollView)
        scrollView.snp.makeConstraints { make in
            make.top.equalTo(topView.snp.bottom)
            make.left.right.bottom.equalToSuperview()
        }
        
        let view = UIView()
        scrollView.addSubview(view)
        
        view.snp.makeConstraints { make in
            make.edges.equalToSuperview()
            make.width.equalToSuperview()
        }

        // Add UI
        view.addSubview(containerView)
        containerView.snp.makeConstraints { make in
            make.top.left.right.equalToSuperview()
            make.height.equalTo(scrollView).multipliedBy(0.4)
        }
        
        containerView.addSubview(localView)
        localView.snp.makeConstraints { make in
            make.left.top.equalTo(self.containerView)
            make.width.height.equalTo(self.containerView)
        }
        
        view.addSubview(roomSettingItem)
        view.addSubview(userSettingItem)
        view.addSubview(joinButton)
        
        roomSettingItem.snp.makeConstraints { make in
            make.top.equalTo(containerView.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.height.equalTo(30)
        }
        
        userSettingItem.snp.makeConstraints { make in
            make.centerY.equalTo(roomSettingItem)
            make.left.equalTo(roomSettingItem.snp.right).offset(20)
            make.right.equalToSuperview().offset(-10)
            make.width.height.equalTo(roomSettingItem)
        }
        
        joinButton.snp.makeConstraints { make in
            make.top.equalTo(roomSettingItem.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
            make.height.equalTo(36)
        }
        
        view.addSubview(effectLabel)
        effectLabel.snp.makeConstraints { make in
            make.top.equalTo(joinButton.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(10)
        }
        
        view.addSubview(voiceReverbSheetView)
        view.addSubview(pitchSetting)

        voiceReverbSheetView.snp.makeConstraints { make in
            make.top.equalTo(effectLabel.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        pitchSetting.snp.makeConstraints { make in
            make.top.equalTo(voiceReverbSheetView.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
            make.right.equalToSuperview().offset(-10)
        }
        
        view.addSubview(reverbConfigLabel)
        view.addSubview(roomSizeSetting)
        view.addSubview(decayTimeSetting)
        view.addSubview(dampingSetting)
        view.addSubview(wetGainSetting)
        view.addSubview(dryGainSetting)
        view.addSubview(preDelaySetting)
        view.addSubview(modifyReverbButton)
        
        reverbConfigLabel.snp.makeConstraints { make in
            make.top.equalTo(pitchSetting.snp.bottom).offset(30)
            make.left.equalTo(pitchSetting)
            make.right.equalToSuperview().offset(-10)
        }
        
        roomSizeSetting.snp.makeConstraints { make in
            make.top.equalTo(reverbConfigLabel.snp.bottom).offset(20)
            make.left.equalTo(reverbConfigLabel)
            make.right.equalToSuperview().offset(-10)
        }
        
        decayTimeSetting.snp.makeConstraints { make in
            make.top.equalTo(roomSizeSetting.snp.bottom).offset(20)
            make.left.equalTo(reverbConfigLabel)
            make.right.equalToSuperview().offset(-10)
        }
        
        dampingSetting.snp.makeConstraints { make in
            make.top.equalTo(decayTimeSetting.snp.bottom).offset(20)
            make.left.equalTo(roomSizeSetting)
            make.right.equalToSuperview().offset(-10)
        }
        
        wetGainSetting.snp.makeConstraints { make in
            make.top.equalTo(dampingSetting.snp.bottom).offset(20)
            make.left.equalTo(dampingSetting)
            make.right.equalToSuperview().offset(-10)
        }
        
        dryGainSetting.snp.makeConstraints { make in
            make.top.equalTo(wetGainSetting.snp.bottom).offset(20)
            make.left.equalTo(wetGainSetting)
            make.right.equalToSuperview().offset(-10)
        }
        
        preDelaySetting.snp.makeConstraints { make in
            make.top.equalTo(dryGainSetting.snp.bottom).offset(20)
            make.left.equalTo(dryGainSetting)
            make.right.equalToSuperview().offset(-10)
        }
        
        modifyReverbButton.snp.makeConstraints { make in
            make.top.equalTo(preDelaySetting.snp.bottom).offset(20)
            make.left.equalTo(preDelaySetting)
            make.right.equalToSuperview().offset(-10)
        }
        
        view.addSubview(ansLabel)
        view.addSubview(voiceAnsSheetView)
        
        ansLabel.snp.makeConstraints { make in
            make.top.equalTo(modifyReverbButton.snp.bottom).offset(20)
            make.left.equalTo(modifyReverbButton)
        }
        
        voiceAnsSheetView.snp.makeConstraints { make in
            make.top.equalTo(ansLabel.snp.bottom).offset(10)
            make.left.equalTo(modifyReverbButton)
            make.right.equalToSuperview().offset(-10)
            make.bottom.equalToSuperview().offset(-10)
        }

    }
    
    // MARK: Lazy laod
    lazy var scrollView: UIScrollView = {
        let scrollView = UIScrollView()
        scrollView.showsVerticalScrollIndicator = false
        scrollView.isUserInteractionEnabled = true
        let tap = UITapGestureRecognizer(target: self, action: #selector(scrollViewAction))
        scrollView.addGestureRecognizer(tap)
        return scrollView
    }()
    
    lazy var roomSettingItem: TextFieldView = {
        let settingView = TextFieldView()
        settingView.title = LocalizedString("hint_room_id")
        return settingView
    }()
    
    lazy var userSettingItem: TextFieldView = {
        let settingView = TextFieldView()
        settingView.title = LocalizedString("hint_user_id")
        return settingView
    }()
    
    lazy var joinButton: UIButton = {
        let button = BaseButton()
        button.setTitle(LocalizedString("button_join_room"), for: .normal)
        button.addTarget(self, action: #selector(joinRoom), for: .touchUpInside)
        return button
    }()
    
    lazy var effectLabel: UILabel = {
        let label = UILabel()
        label.text = LocalizedString("label_effect")
        label.font = UIFont.boldSystemFont(ofSize: 18)
        return label
    }()
    
    lazy var voiceReverbSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_voice_reverb"), optionArray: ["Original","Echo","Concert","Ethereal","KTV","Studio","VirtualStereo","Spacious","3D"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var pitchSetting: SliderView = {
        let settingView = SliderView(minValue: -12, maxValue: 12, defaultValue: 0)
        settingView.title = LocalizedString("label_voice_pitch")
        return settingView
    }()
    
    lazy var reverbConfigLabel: UILabel = {
        let label = UILabel()
        label.text = LocalizedString("label_voice_reverb_switch")
        label.font = effectLabel.font
        return label
    }()
    
    lazy var roomSizeSetting: SliderView = {
        let settingView = SliderView(minValue: 0, maxValue: 100, defaultValue: 50)
        settingView.title = LocalizedString("label_room_size")
        return settingView
    }()
    
    lazy var decayTimeSetting: SliderView = {
        let settingView = SliderView(minValue: 0, maxValue: 100, defaultValue: 50)
        settingView.title = LocalizedString("label_decay_time")
        return settingView
    }()
    
    lazy var dampingSetting: SliderView = {
        let settingView = SliderView(minValue: 0, maxValue: 100, defaultValue: 50)
        settingView.title = LocalizedString("label_damping")
        return settingView
    }()
    
    lazy var wetGainSetting: SliderView = {
        let settingView = SliderView(minValue: -20, maxValue: 10, defaultValue: 0)
        settingView.title = LocalizedString("label_wet_gain")
        return settingView
    }()
    
    lazy var dryGainSetting: SliderView = {
        let settingView = SliderView(minValue: -20, maxValue: 10, defaultValue: 0)
        settingView.title = LocalizedString("label_dry_gain")
        return settingView
    }()
    
    lazy var preDelaySetting: SliderView = {
        let settingView = SliderView(minValue: 0, maxValue: 200, defaultValue: 0)
        settingView.title = LocalizedString("label_pre_delay")
        return settingView
    }()
    
    lazy var modifyReverbButton: UIButton = {
        let button = BaseButton()
        button.setTitle(LocalizedString("button_confirm_changes"), for: .normal)
        button.addTarget(self, action: #selector(modifyReverbConfig), for: .touchUpInside)
        return button
    }()
    
    lazy var ansLabel: UILabel = {
        let label = UILabel()
        label.text = LocalizedString("label_ans_mode")
        label.font = effectLabel.font
        return label
    }()
    
    lazy var voiceAnsSheetView: ActionSheetView = {
        let actionSheetView = ActionSheetView.init(title: LocalizedString("label_ans_mode"), optionArray: ["Disable","Low","Medium","High","Automatic"], defaultIndex: 0)
        actionSheetView.presentingViewController = self
        
        return actionSheetView
    }()
    
    lazy var containerView: UIView = {
        let view = UIView.init()
        view.backgroundColor = .groupTableViewBackground
        return view
    }()
    
    lazy var localView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    // MARK: ByteRTCVideoDelegate & ByteRTCRoomDelegate
    // Room entry status
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onRoomStateChanged roomId: String, withUid uid: String, state: Int, extraInfo: String) {
        ToastComponents.shared.show(withMessage: "onRoomStateChanged uid: \(uid) state:\(state)")
        
    }
}
