/**
* 功能名称： VolcEngineRTC 快速开始
* 功能简单描述：快速跑通 ByteRTC 音视频通话功能
*
* 此功能涉及的API及回调：
*     createRTCEngine 创建引擎
*     destroyRTCEngine 销毁引擎
*     startAudioCapture 开启音频采集
*     startVideoCapture 开启视频采集
*     createRTCRoom 创建RTC房间
*     joinRoom 进入RTC房间
*     leaveRoom 离开RTC房间
*     destroy 销毁RTC房间
*
*     onRoomStateChanged 房间状态回调
*     onLeaveRoom 离房回调
*     onUserJoined 用户加入回调
*     onUserLeave  用户离开回调
*     onUserPublishStream 用户发流回调
*     onUserUnpublishStream 用户停止发流回调
*
*
* Demo实现时的逻辑
*    请按照界面给出的步骤开发音视频通话功能
*    为了展示简单，所有功能的token都由客户端TokenGenerator类生成，请在真正接入时视具体情况而定
*/

/**
* Function name: BytePlusRTC Quick Start
* Function simple description: Quickly run through ByteRTC audio & video call function
* Reminder:
* 1. Please follow the steps given on the interface to develop the audio & video call function
* 2. To demonstrate, all functional tokens are generated by the client side TokenGenerator class, please depend on the specific situation when actually accessing
*/

import UIKit
import SnapKit
import BytePlusRTC

class QuickStartViewController: BaseViewController, ByteRTCEngineDelegate, ByteRTCRoomDelegate {
    
    var rtcVideo: ByteRTCEngine?
    var rtcRoom: ByteRTCRoom?
    var userVideoStreamMap: Dictionary = Dictionary<String, ByteRTCStreamInfo>()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.createUI()
        self.buildActions()
    }
    
    deinit {
        self.rtcRoom?.leave()
        self.rtcRoom?.destroy()
        self.rtcRoom = nil
        
        ByteRTCEngine.destroyRTCEngine()
        self.rtcVideo = nil
    }
    
    // MARK: Private method
    
    func buildActions() {
        stepButton1.buttonAction = { [weak self] in
            if self?.rtcVideo == nil {
                // 创建引擎
                let engineCfg = ByteRTCEngineConfig.init()
                engineCfg.appID = kAppID
                engineCfg.parameters = [:]
                self?.rtcVideo = ByteRTCEngine.createRTCEngine(engineCfg, delegate: self)
            }
        }
        
        stepButton2.buttonAction = { [weak self] in
            if self?.rtcVideo != nil {
                // 开启本地音视频采集
                self?.rtcVideo?.startVideoCapture()
                self?.rtcVideo?.startAudioCapture()
            }
        }
        
        stepButton3.buttonAction = { [weak self] in
            if self?.rtcVideo != nil {
                // 设置本地渲染
                self?.bindLocalRenderView()
            }
        }
        
        stepButton4.buttonAction = { [weak self] in
            if self?.rtcVideo != nil {
                // 加入房间
                self?.joinRoom()
            } else {
                ToastComponents.shared.show(withMessage: "RTCVideo has't been created")
            }
        }
        
        stepButton6.buttonAction = { [weak self] in
            if self?.rtcRoom != nil {
                // 离开房间
                self?.rtcRoom?.leave()
            }
        }
        
        stepButton7.buttonAction = { [weak self] in
            if self?.rtcRoom != nil {
                // 销毁房间
                self?.rtcRoom?.destroy()
                self?.rtcRoom = nil
            }
        }
        
        stepButton8.buttonAction = { [weak self] in
            self?.localView.userId = ""
            if self?.rtcVideo != nil {
                // 销毁引擎
                ByteRTCEngine.destroyRTCEngine()
                self?.rtcVideo = nil
            }
        }
    }
    
    @objc func joinRoom()  {
        let roomId = self.roomTextField.text ?? ""
        let userId = self.userTextField.text ?? ""
        
        var vaild = checkValid(roomId)
        if vaild == false {
            ToastComponents.shared.show(withMessage:getString(key: "roomidUidCheckFailHint") )
            return
        }
        
        vaild = checkValid(userId)
        if vaild == false {
            ToastComponents.shared.show(withMessage: getString(key: "roomidUidCheckFailHint"))
            return
        }
        
        // 加入房间
        self.rtcRoom = self.rtcVideo?.createRTCRoom(roomId)
        self.rtcRoom?.delegate = self
        
        // 获取token,建议从服务端获取
        let token = generatorToken(roomId: roomId, userId: userId)
        
        let userInfo = ByteRTCUserInfo.init()
        userInfo.userId = userId
        
        let roomCfg = ByteRTCRoomConfig.init()
        roomCfg.isPublishAudio = true
        roomCfg.isPublishVideo = true
        roomCfg.isAutoSubscribeAudio = true
        roomCfg.isAutoSubscribeVideo = true
        
        self.rtcRoom?.joinRoom(token, userInfo: userInfo, userVisibility: true, roomConfig: roomCfg)
    }
    
    func bindLocalRenderView() {
        // 设置本地渲染视图
        let userId = self.userTextField.text ?? ""
        self.localView.userId = userId
        
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = self.localView.videoView
        canvas.renderMode = .hidden
        
        self.rtcVideo?.setLocalVideoCanvas(withCanvas: canvas);
    }
    
    func bindRemoteRenderView(view: UserVideoView, roomId: String, userId: String) {
        // 设置远端用户视频渲染视图
        var streamInfo = self.userVideoStreamMap[userId]
        if streamInfo == nil {
            return
        }
        var streamId = streamInfo?.streamId
        if streamId == nil {
            return
        }
        
        let canvas = ByteRTCVideoCanvas.init()
        canvas.view = view.videoView
        canvas.renderMode = .hidden
        view.userId = userId
        
        self.rtcVideo?.setRemoteVideoCanvas(streamId!, withCanvas: canvas)
    }
    
    func removeRemoteRenderView(view: UserVideoView, roomId: String, userId: String) {
        // 移除远端用户视频渲染视图
        var streamInfo = self.userVideoStreamMap[userId]
        if streamInfo == nil {
            return
        }
        var streamId = streamInfo?.streamId
        if streamId == nil {
            return
        }
        
        let canvas = ByteRTCVideoCanvas.init()
        // view置为空
        canvas.view = nil
        canvas.renderMode = .hidden
        view.userId = ""
        
        let streamKey = ByteRTCRemoteStreamKey.init()
        streamKey.userId = userId;
        streamKey.roomId = roomId;
        streamKey.streamIndex = .indexMain
        
        self.rtcVideo?.setRemoteVideoCanvas(streamId!, withCanvas: canvas)
    }
    
    func createUI() -> Void {
        // 添加视图
        view.addSubview(containerView)
        self.containerView.addSubview(localView)
        self.containerView.addSubview(remoteView)
        
        containerView.snp.makeConstraints { make in
            make.top.equalTo(topView.snp.bottom)
            make.left.right.equalTo(self.view)
        }
        
        self.localView.snp.makeConstraints { make in
            make.left.top.equalTo(self.containerView)
            make.height.equalTo(self.containerView)
            make.width.equalTo(self.containerView).multipliedBy(0.5)
        }
        
        self.remoteView.snp.makeConstraints { make in
            make.right.bottom.equalTo(self.containerView)
            make.height.equalTo(self.containerView)
            make.width.equalTo(self.containerView).multipliedBy(0.5)
        }
        
        view.addSubview(roomTextField)
        view.addSubview(userTextField)
        view.addSubview(stepButton1)
        view.addSubview(stepButton2)
        view.addSubview(stepButton3)
        view.addSubview(stepButton4)
        view.addSubview(stepLabel5)
        view.addSubview(stepButton6)
        view.addSubview(stepButton7)
        view.addSubview(stepButton8)
        
        roomTextField.snp.makeConstraints { make in
            make.left.equalToSuperview().offset(10)
            make.height.equalTo(32)
            make.top.lessThanOrEqualTo(containerView.snp.bottom).offset(10)
        }
        
        userTextField.snp.makeConstraints { make in
            make.centerY.equalTo(roomTextField)
            make.left.equalTo(roomTextField.snp.right).offset(20)
            make.right.equalToSuperview().offset(-10)
            make.width.equalTo(roomTextField)
            make.height.equalTo(32)
        }
        
        stepButton1.snp.makeConstraints { make in
            make.top.equalTo(roomTextField.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton2.snp.makeConstraints { make in
            make.top.equalTo(stepButton1.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton3.snp.makeConstraints { make in
            make.top.equalTo(stepButton2.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton4.snp.makeConstraints { make in
            make.top.equalTo(stepButton3.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepLabel5.snp.makeConstraints { make in
            make.top.equalTo(stepButton4.snp.bottom).offset(10)
            make.left.equalToSuperview().offset(10)
        }
        
        stepButton6.snp.makeConstraints { make in
            make.top.equalTo(stepLabel5.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton7.snp.makeConstraints { make in
            make.top.equalTo(stepButton6.snp.bottom).offset(10)
            make.left.right.equalToSuperview()
        }
        
        stepButton8.snp.makeConstraints { make in
            make.top.equalTo(stepButton7.snp.bottom).offset(10)
            make.bottom.equalTo(self.view.snp.bottom).offset(-20)
            make.left.right.equalToSuperview()
        }
    }
    
    // MARK: lazyload
    lazy var roomTextField: UITextField = {
        let textField = UITextField()
        textField.placeholder = getString(key: "inputRoomIdHint")
        textField.borderStyle = .roundedRect
        return textField
    }()
    
    lazy var userTextField: UITextField = {
        let textField = UITextField()
        textField.placeholder = getString(key: "inputUserIdHint")
        textField.borderStyle = .roundedRect
        return textField
    }()
    
    lazy var stepButton1: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step1CreateEngine"), buttonText: getString(key: "createEngine"))
        
        return stepButton
    }()
    
    lazy var stepButton2: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step2StartCapture"), buttonText: getString(key: "startCapture"))
        
        return stepButton
    }()
    lazy var stepButton3: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step3SetLocalCanvas"), buttonText: getString(key: "setLocalCanvas"))
        
        return stepButton
    }()
    
    lazy var stepButton4: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step4JoinRoom"), buttonText: getString(key: "joinRoom"))
        
        return stepButton
    }()
    
    lazy var stepLabel5: UILabel = {
        let label = UILabel.init()
        label.textAlignment = .center
        label.font = UIFont.systemFont(ofSize: 16)
        label.text = getString(key: "step5SetRemoteCanvas")
        return label
    }()
    
    lazy var stepButton6: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step6LeaveRoom"), buttonText: getString(key: "leaveRoom"))
        
        return stepButton
    }()
    lazy var stepButton7: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step7DestoryRoom"), buttonText: getString(key: "destoryRoom"))
        
        return stepButton
    }()
    lazy var stepButton8: StepButton = {
        let stepButton = StepButton.init(labelText: getString(key: "step8DestoryEngine"), buttonText: getString(key: "destoryEngine"))
        
        return stepButton
    }()
    
    lazy var containerView: UIView = {
        let view = UIView.init()
        view.backgroundColor = .groupTableViewBackground
        return view
    }()
    
    lazy var localView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    lazy var remoteView: UserVideoView = {
        let view = UserVideoView.init()
        return view
    }()
    
    // MARK: ByteRTCEngineDelegate & ByteRTCRoomDelegate
    //进房状态
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onRoomStateChanged roomId: String, withUid uid: String, state: Int, extraInfo: String) {
        ToastComponents.shared.show(withMessage: "onRoomStateChanged uid: \(uid) state:\(state)")
        
        if state == 0 {
            print("Join Room Success")
        }
    }
    
    // 远端用户发布流
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserPublishStreamVideo streamId: String, info: ByteRTCStreamInfo, isPublish: Bool) {
        self.userVideoStreamMap.updateValue(info, forKey: info.userId)
        ToastComponents.shared.show(withMessage: "onUserPublishStreamVideo uid: \(info.userId), isPub: \(isPublish)")
        // 渲染远端用户
        if isPublish {
            DispatchQueue.main.async {
                self.bindRemoteRenderView(view: self.remoteView, roomId: info.roomId, userId: info.userId)
            }
        } else {
            // 移除UI显示
            DispatchQueue.main.async {
                // 移除远端视图
                if info.userId == self.remoteView.userId {
                    self.removeRemoteRenderView(view: self.remoteView, roomId: info.roomId, userId: info.userId)
                }
            }
        }
    }
    
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserPublishStreamAudio streamId: String, info: ByteRTCStreamInfo, isPublish: Bool) {
        ToastComponents.shared.show(withMessage: "onUserPublishStreamAudio uid: \(info.userId), isPub: \(isPublish)")
    }
    
    // 远端用户加入房间
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserJoined userInfo: ByteRTCUserInfo) {
        ToastComponents.shared.show(withMessage: "onUserJoined uid: \(userInfo.userId)")
    }
    
    // 远端用户离开房间
    func rtcRoom(_ rtcRoom: ByteRTCRoom, onUserLeave uid: String, reason: ByteRTCUserOfflineReason) {
        ToastComponents.shared.show(withMessage: "onUserLeave uid: \(uid)")
    }
    
    func onTokenWillExpire(_ rtcRoom: ByteRTCRoom) {
       // token 即将过期
        ToastComponents.shared.show(withMessage: getString(key: "tokenExpireHint"))
    }
}
