package com.vertc.api.example.examples.video;

import android.os.Bundle;
import android.util.DisplayMetrics;
import android.util.Log;
import android.view.TextureView;
import android.widget.FrameLayout;

import androidx.annotation.MainThread;
import androidx.annotation.NonNull;

import com.ss.bytertc.engine.RTCRoom;
import com.ss.bytertc.engine.RTCRoomConfig;
import com.ss.bytertc.engine.RTCEngine;
import com.ss.bytertc.engine.UserInfo;
import com.ss.bytertc.engine.VideoCanvas;
import com.ss.bytertc.engine.data.StreamInfo;
import com.ss.bytertc.engine.handler.IRTCRoomEventHandler;
import com.ss.bytertc.engine.handler.IRTCEngineEventHandler;
import com.ss.bytertc.engine.live.MixedStreamLayoutRegionConfig;
import com.ss.bytertc.engine.live.MixedStreamConfig;
import com.ss.bytertc.engine.live.MixedStreamMediaType;
import com.ss.bytertc.engine.live.MixedStreamPushTargetConfig;
import com.ss.bytertc.engine.live.MixedStreamPushTargetType;
import com.ss.bytertc.engine.live.MixedStreamRenderMode;
import com.ss.bytertc.engine.live.MixedStreamTaskErrorCode;
import com.ss.bytertc.engine.live.MixedStreamTaskEvent;
import com.ss.bytertc.engine.live.MixedStreamTaskInfo;
import com.ss.bytertc.engine.live.MixedStreamVideoType;
import com.ss.bytertc.engine.type.ChannelProfile;
import com.ss.bytertc.engine.type.MediaStreamType;
import com.ss.bytertc.engine.type.RTCRoomStats;
import com.ss.bytertc.engine.type.StreamRemoveReason;
import com.vertc.api.example.R;
import com.vertc.api.example.base.ExampleBaseActivity;
import com.vertc.api.example.base.ExampleCategory;
import com.vertc.api.example.base.annotation.ApiExample;
import com.vertc.api.example.databinding.ActivityCdnStreamBinding;
import com.vertc.api.example.utils.IMEUtils;
import com.vertc.api.example.utils.RTCHelper;
import com.vertc.api.example.utils.RTMPLinkGenerator;
import com.vertc.api.example.utils.RemoteView;
import com.vertc.api.example.utils.ToastUtil;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

/**
 * <pre>
 * Function name: BytePlusRTC push stream to CDN.
 * Function brief: You can combine multiple audio and video streams from within an video call into a single stream. This merged stram can then be pushed to a specified streaming address, typically a CDN (Content Delivery Network) address.
 * Notes:
 *  1. This demo demonstrates pushing mixed stream to CDN,
 *  1.1 When using a layout that displays 4 views in 1 row, each stream will occupy a width of 0.25 and a height of 1 in the layout.
 *  1.2 In a four-grid layout, each stream will occupy a width of 0.5 and a height of 0.5 within the layout.
 *  1.3 Up to four streams can be displayed in the room.
 *  2. For demonstration purposes, all tokens for the functionalities are generated by the client-side TokenGenerator class. However, please adjust accordingly based on the specific circumstances when integrating in a real environment.
 * Reference document: https://docs.byteplus.com/en/docs/byteplus-rtc/docs-69817
 * </pre>
 */
@ApiExample(title = "Push Stream to CDN", category = ExampleCategory.VIDEO, order = 4)
public class CDNStreamActivity extends ExampleBaseActivity {
    private static final String TAG = "CDNStreamActivity";
    private String roomID;
    private static final String CDN_TASK_ID = "1";
    private FrameLayout localViewContainer;
    @NonNull
    private List<RemoteView> mRemoteViews = Collections.emptyList();
    private final List<String> allRemoteUserIds = new ArrayList<>();
    private RTCEngine rtcVideo;
    private RTCRoom rtcRoom;

    private MixedStreamConfig mixedStreamConfig;
    ActivityCdnStreamBinding binding;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        binding = ActivityCdnStreamBinding.inflate(getLayoutInflater());

        setContentView(binding.getRoot());

        binding.content.setOnClickListener(IMEUtils::closeIME);

        initUI(binding);

        rtcVideo = RTCHelper.createRTCVideo(this, videoEventHandler, "cdn-stream");
        setLocalRenderView();
        rtcVideo.startVideoCapture();
        rtcVideo.startAudioCapture();

        mixedStreamConfig = MixedStreamConfig.defaultMixedStreamConfig();
    }

    private void initUI(ActivityCdnStreamBinding binding) {
        localViewContainer = binding.localViewContainer;
        mRemoteViews = Arrays.asList(
                RemoteView.of(binding.remoteViewContainer1),
                RemoteView.of(binding.remoteViewContainer2),
                RemoteView.of(binding.remoteViewContainer3)
        );

        binding.btnJoinRoom.setOnClickListener(v -> {
            if (v.isSelected()) {
                leaveRoom();

                v.setSelected(false);
                binding.btnJoinRoom.setText(R.string.button_join_room);
                return;
            }
            String roomId = binding.roomIdInput.getText().toString();
            if (!RTCHelper.checkValid(roomId)) {
                ToastUtil.showToast(this, R.string.toast_check_valid_false);
                return;
            }
            joinRoom(roomId);
            v.setSelected(true);
            binding.btnJoinRoom.setText(R.string.button_leave_room);

            String rtmpUrl = RTMPLinkGenerator.create(CDN_TASK_ID);
            if (rtmpUrl != null) {
                binding.cdnAddressInput.setText(rtmpUrl);
            }
        });

        binding.btnStartPush.setOnClickListener(v -> startPushCDNStream());
        binding.btnUpdatePushConfig.setOnClickListener(v -> updateCDNStreamConfig());
        binding.btnStopPush.setOnClickListener(v -> stopPushCDNStream());
    }

    private void setLocalRenderView() {
        TextureView textureView = new TextureView(this);
        localViewContainer.removeAllViews();
        localViewContainer.addView(textureView);

        VideoCanvas videoCanvas = new VideoCanvas();
        videoCanvas.renderView = textureView;
        videoCanvas.renderMode = VideoCanvas.RENDER_MODE_HIDDEN;
        rtcVideo.setLocalVideoCanvas(videoCanvas);
    }

    @MainThread
    void setRemoteRenderView(String streamId, String uid) {
        if (streamId == null) {
            return;
        }
        for (RemoteView remoteView : mRemoteViews) {
            if (remoteView.isEmpty()) {
                TextureView textureView = new TextureView(this);

                remoteView.attach(uid, streamId, textureView);

                VideoCanvas videoCanvas = new VideoCanvas();
                videoCanvas.renderView = textureView;
                videoCanvas.renderMode = VideoCanvas.RENDER_MODE_HIDDEN;
                rtcVideo.setRemoteVideoCanvas(streamId, videoCanvas);
                break;
            }
        }
    }

    @MainThread
    void removeRemoteView(String streamId) {
        if (streamId == null) {
            return;
        }
        for (RemoteView remoteView : mRemoteViews) {
            if (streamId.equals(remoteView.getStreamId())) {
                rtcVideo.setRemoteVideoCanvas(streamId, null);
                remoteView.detach();
                break;
            }
        }
    }

    void clearRemoteViews() {
        for (RemoteView remoteView : mRemoteViews) {
            String streamId = remoteView.getStreamId();
            if (streamId != null) {
                rtcVideo.setRemoteVideoCanvas(streamId, null);
                remoteView.detach();
            }
        }
    }

    private void joinRoom(String roomId) {
        requestRoomToken(roomId, localUid, token -> {
            this.roomID = roomId;
            rtcRoom = rtcVideo.createRTCRoom(roomId);
            rtcRoom.setRTCRoomEventHandler(rtcRoomEventHandler);
            UserInfo userInfo = new UserInfo(localUid, "");
            boolean isAutoPublish = true;
            boolean isAutoSubscribeAudio = true;
            boolean isAutoSubscribeVideo = true;
            RTCRoomConfig roomConfig = new RTCRoomConfig(
                    ChannelProfile.CHANNEL_PROFILE_CHAT_ROOM,
                    isAutoPublish,
                    isAutoPublish,
                    isAutoSubscribeAudio,
                    isAutoSubscribeVideo);
            rtcRoom.joinRoom(token, userInfo, true, roomConfig);
        });
    }

    private void leaveRoom() {
        allRemoteUserIds.clear();
        clearRemoteViews();

        if (rtcRoom != null) {
            rtcRoom.leaveRoom();
            rtcRoom.destroy();
            rtcRoom = null;
        }
    }

    private void startPushCDNStream() {
        String cdnAddr = binding.cdnAddressInput.getText().toString();
        if (cdnAddr.isEmpty()) {
            ToastUtil.showToast(this, R.string.toast_cdn_url_is_empty);
            return;
        }
        Log.d(TAG, "url=" + cdnAddr);

        String backgroundColor = binding.layoutColorInput.getText().toString();

        mixedStreamConfig.userID = localUid;
        mixedStreamConfig.roomID = roomID;
        mixedStreamConfig.backgroundColor = backgroundColor;
        mixedStreamConfig.regions = getLayoutRegions();

        MixedStreamPushTargetConfig targetConfig = new MixedStreamPushTargetConfig();
        targetConfig.pushTargetType = MixedStreamPushTargetType.PUSH_TO_CDN;
        targetConfig.pushCDNURL = cdnAddr;

        rtcVideo.startPushMixedStream(CDN_TASK_ID, targetConfig, mixedStreamConfig);
    }

    private void updateCDNStreamConfig() {
        String cdnAddr = binding.cdnAddressInput.getText().toString();
        if (cdnAddr.isEmpty()) {
            ToastUtil.showToast(this, R.string.toast_cdn_url_is_empty);
            return;
        }
        Log.d(TAG, "url=" + cdnAddr);

        String backgroundColor = binding.layoutColorInput.getText().toString();

        mixedStreamConfig.backgroundColor = backgroundColor;
        mixedStreamConfig.regions = getLayoutRegions();

        MixedStreamPushTargetConfig targetConfig = new MixedStreamPushTargetConfig();
        targetConfig.pushTargetType = MixedStreamPushTargetType.PUSH_TO_CDN;
        targetConfig.pushCDNURL = cdnAddr;

        rtcVideo.updatePushMixedStream(CDN_TASK_ID, targetConfig, mixedStreamConfig);
    }

    private void stopPushCDNStream() {
        rtcVideo.stopPushMixedStream(CDN_TASK_ID, MixedStreamPushTargetType.PUSH_TO_CDN);
    }

    private MixedStreamLayoutRegionConfig[] getLayoutRegions() {
        String mode = (String) binding.layoutModeSpinner.getSelectedItem();
        boolean is1x4 = "1x4".equals(mode);

        List<String> userIds = new ArrayList<>();
        userIds.add(localUid);
        userIds.addAll(allRemoteUserIds);
        int userNum = Math.min(4, userIds.size());

        MixedStreamLayoutRegionConfig[] regions = new MixedStreamLayoutRegionConfig[userNum];
        for (int index = 0; index < userNum; index++) {
            if (is1x4) {
                regions[index] = createRegion1x4(userIds, index);
            } else {
                regions[index] = createRegion2x2(userIds, index);
            }
        }
        return regions;
    }

    @NonNull
    private MixedStreamLayoutRegionConfig createRegion1x4(List<String> userIds, int index) {
        final String uid = userIds.get(index);
        int regionWidth = mixedStreamConfig.videoConfig.width / 4;
        int regionHeight = mixedStreamConfig.videoConfig.height;
        MixedStreamLayoutRegionConfig region = new MixedStreamLayoutRegionConfig();
        region.roomID = roomID;
        region.userID = uid;
        region.locationX = regionWidth * index;
        region.locationY = 0;
        region.width = regionWidth;
        region.height = regionHeight;
        region.alpha = 1.0;
        region.zOrder = 0;
        region.renderMode = MixedStreamRenderMode.MIXED_STREAM_RENDER_MODE_HIDDEN;
        region.streamType = MixedStreamVideoType.MIXED_STREAM_VIDEO_TYPE_MAIN;
        region.mediaType = MixedStreamMediaType.MIXED_STREAM_MEDIA_TYPE_AUDIO_AND_VIDEO;
        return region;
    }

    @NonNull
    private MixedStreamLayoutRegionConfig createRegion2x2(List<String> userIds, int index) {
        final String uid = userIds.get(index);
        int regionWidth = mixedStreamConfig.videoConfig.width / 2;
        int regionHeight = mixedStreamConfig.videoConfig.height / 2;
        MixedStreamLayoutRegionConfig region = new MixedStreamLayoutRegionConfig();
        region.roomID = roomID;
        region.userID = uid;
        region.locationX = (index % 2) * regionWidth;
        region.locationY = (index / 2) * regionHeight;
        region.width = regionWidth;
        region.height = regionHeight;
        region.alpha = 1.0;
        region.zOrder = 0;
        region.renderMode = MixedStreamRenderMode.MIXED_STREAM_RENDER_MODE_HIDDEN;
        region.streamType = MixedStreamVideoType.MIXED_STREAM_VIDEO_TYPE_MAIN;
        region.mediaType = MixedStreamMediaType.MIXED_STREAM_MEDIA_TYPE_AUDIO_AND_VIDEO;
        return region;
    }

    final IRTCRoomEventHandler rtcRoomEventHandler = new IRTCRoomEventHandler() {
        @Override
        public void onRoomStateChanged(String roomId, String uid, int state, String extraInfo) {
            super.onRoomStateChanged(roomId, uid, state, extraInfo);
            String info = String.format(Locale.ENGLISH, "roomId:%s, uid:%s, state:%d, extraInfo:%s", roomId, uid, state, extraInfo);
            ToastUtil.showLongToast(CDNStreamActivity.this, info);
        }

        @Override
        public void onUserPublishStreamVideo(String streamId, StreamInfo streamInfo, boolean isPublish) {
            if (isPublish) {
                runOnUiThread(() -> setRemoteRenderView(streamId, streamInfo.getUserId()));
            } else {
                runOnUiThread(() -> removeRemoteView(streamId));
            }
        }

        @Override
        public void onUserPublishStreamAudio(String streamId, StreamInfo streamInfo, boolean isPublish) {
            if (isPublish) {
                runOnUiThread(() -> setRemoteRenderView(streamId, streamInfo.getUserId()));
            } else {
                runOnUiThread(() -> removeRemoteView(streamId));
            }
        }

        @Override
        public void onUserJoined(UserInfo userInfo) {
            super.onUserJoined(userInfo);
            Log.i(TAG, "onUserJoined, uid:" + userInfo.getUid());
            ToastUtil.showToast(CDNStreamActivity.this, "onUserJoined, uid:" + userInfo.getUid());
            runOnUiThread(() -> allRemoteUserIds.add(userInfo.getUid()));
        }

        @Override
        public void onUserLeave(String uid, int reason) {
            super.onUserLeave(uid, reason);
            runOnUiThread(() -> allRemoteUserIds.remove(uid));
        }

        @Override
        public void onLeaveRoom(RTCRoomStats stats) {
            super.onLeaveRoom(stats);
            ToastUtil.showLongToast(CDNStreamActivity.this, "onLeaveRoom, stats:" + stats.toString());
        }
    };

    final IRTCEngineEventHandler videoEventHandler = new IRTCEngineEventHandler() {
        @Override
        public void onMixedStreamEvent(MixedStreamTaskInfo info, MixedStreamTaskEvent event, MixedStreamTaskErrorCode error) {
            super.onMixedStreamEvent(info, event, error);
            String msg = String.format(Locale.ENGLISH, "onMixedStreamEvent, taskId:%s, event:%s, error:%s", info.getTaskId(), event.toString(), error.toString());
            Log.d(TAG, msg);
            ToastUtil.showLongToast(CDNStreamActivity.this, msg);
        }
    };

    @Override
    protected void onDestroy() {
        super.onDestroy();
        leaveRoom();
        if (rtcVideo != null) {
            rtcVideo.stopAudioCapture();
            rtcVideo.stopVideoCapture();
            stopPushCDNStream();
        }
        RTCEngine.destroyRTCEngine();
        rtcVideo = null;
    }
}
